### ISSUE TITLE
Large pictures are not fully displayed

### ISSUE THREAD

**Issue by Zengyf-CVer** [pngwn/gradio-imageslider#15]
@pngwn 
I entered a large remote sensing image, but it was not fully displayed using gradient_imageslider.
OS: macOS
gradio: 4.21.0
gradio_imageslider: 0.0.18

Download address of this picture: https://github.com/Zengyf-CVer/imgs/blob/main/P0017.png

Sample code：
```python
import gradio as gr
from gradio_imageslider import ImageSlider


def a(img):
    return (img, img)


with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            with gr.Row():
                input_img = gr.Image()
            with gr.Row():
                btn = gr.Button(value="submit")

        with gr.Column():
            with gr.Row():
                output_img = ImageSlider(position=0.5)

    btn.click(fn=a, inputs=[input_img], outputs=[output_img])

demo.launch(inbrowser=True)
```

![image](https://github.com/pngwn/gradio-imageslider/assets/41098760/baac7b00-18f7-4ff0-838b-5fafd7c308d6)

**Comment by pngwn** [comment]
This seems to work fine with the latest version of gradio `4.27.0`.

Could you retest this demo and reopen the issue if it still persists?

Thanks!
