### ISSUE TITLE
Clearing the image does not reset the slider to halfway through the image

### ISSUE THREAD

**Issue by freddyaboulton** [pngwn/gradio-imageslider#9]
If you clear the image, the slider will stay where it is. I think it would be better if it reset to halfway as that's the "no value" state.

![imageslider](https://github.com/pngwn/gradio-imageslider/assets/41651716/23441b6a-8f13-4f5f-a538-fd46dfddfc67)

**Comment by pngwn** [comment]
Ah, nice catch!
